name: ig_chat_reader
description: "Instagram Chat Reader to simplify reading HTML exports of user messaging data."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.26.8+9

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  rxdart: ^0.28.0
  web: ^1.1.1
  archive: ^4.0.9
  html: ^0.15.6
  intl: ^0.19.0
  flutter_svg: ^2.2.2
  package_info_plus: ^9.0.1
  screenshot: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  image_path: "assets/images/ig_chat_reader.png"
  web:
    generate: true
    image_path: "assets/images/ig_chat_reader.png"
    background_color: "#fff"
    theme_color: "#000"

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/fonts/Quicksand/
  
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand-Bold.ttf
          weight: 700
        - asset: assets/fonts/Quicksand/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand/Quicksand-Light.ttf
          weight: 300
